// The setup questions' own dictionary (EN + pt-BR): titles, questions, hints,
// option labels and previews, lookup notes, step labels and the flag errors of
// a non-interactive run. Keys starting with `vps` or `adv` belong to a rented
// server or to the explicit "Advanced" home choice: only those may talk about
// letting 80/443 in (a test holds every other key to that).
import { defineStrings } from '../strings.ts';

export const q = defineStrings(
  {
    // steps and chrome
    stepWhere: 'Where',
    stepAddress: 'Address',
    stepDiscord: 'Discord',
    stepMedia: 'Video',
    stepPorts: 'Ports',
    stepUpdates: 'Updates',
    stepTray: 'Tray icon',
    stepReview: 'Review',
    stepInstall: 'Install',
    badge: '{step} · Step {n} of {total}',
    required: 'This cannot be empty.',
    notOffered: 'Pick one of the options.',
    locked: 'Answer the earlier steps first',
    actionRetry: 'Try again',
    actionQuit: 'Quit setup',
    actionOpen: 'Open the link in the browser',
    actionAdded: 'I added the bot: check again',
    actionCheck: 'Check again',
    actionTypeAgain: 'Type the token again',
    actionKeep: 'Keep it anyway (the running service retries)',
    openFailed: 'Could not open a browser; open the link by hand.',

    // the machine
    hostChecking: 'Looking at this machine and its network…',
    hostLineIp: 'This machine: {os}, {arch}, public IP {ip}.',
    hostLineNoIp: 'This machine: {os}, {arch}, public IP unknown (offline?).',
    hostRouter: 'Router: {router}.',

    // where
    langTitle: 'Language / Idioma',
    langQ: 'The language of this setup and of the telinha command.',
    langEn: 'English',
    langPt: 'Português (Brasil)',
    hostingTitle: 'Where will Telinha run?',
    hostingQ: 'Pick the machine that stays on and hosts the rooms.',
    hostingHome: 'A computer at home',
    hostingHomeDesc: 'Your PC or a home server, behind your internet router',
    hostingHomePreview:
      'Good for a group of friends: Telinha runs on a machine you already have.\n\nHome internet connections usually do not let the web ports 80 and 443 in, so Telinha does not count on them. Next you pick how people reach this machine: a Cloudflare Tunnel (if you have a domain on Cloudflare) or a free DuckDNS address with HTTPS on port 8443.',
    vpsHosting: 'A rented server (VPS)',
    vpsHostingDesc: 'Hetzner, DigitalOcean, Oracle Cloud and the like: it has its own public IP',
    vpsHostingPreview:
      "A VPS has a public IP and the web ports 80 and 443 reach it, so Telinha gets its HTTPS certificate the usual way.\n\nThe provider's firewall must let Telinha's ports through; setup lists them.",

    // address: home
    homeCfTitle: 'Do you have a domain on Cloudflare?',
    homeCfQ:
      'Home internet connections usually do not let the web ports 80 and 443 in, so Telinha does not count on them.',
    homeCfYes: 'Yes: use a Cloudflare Tunnel',
    homeCfYesDesc: 'Your own address; nothing to open for the pages',
    homeCfYesPreview:
      'Telinha runs cloudflared and Cloudflare forwards https://your.domain to it.\n\nNothing changes on the router for the pages. The screen sharing itself still needs the media ports (a later step).',
    homeCfNo: 'No: use a free DuckDNS address',
    homeCfNoDesc: 'Like https://name.duckdns.org:8443',
    homeCfNoPreview:
      "You get https://<name>.duckdns.org:8443. The certificate comes from Let's Encrypt through your DuckDNS token (DNS-01): nothing to open on 80 or 443.\n\nSome strict networks (offices, schools) only let browsers reach port 443, so people there cannot open the links; a domain on Cloudflare has no such limit.\n\nYou need a free duckdns.org account and its token.",
    advHomeCf: 'Advanced…',
    advHomeCfDesc: 'I opened 80/443 myself, or I run my own reverse proxy',
    advHomeCfPreview:
      'Only if you know your internet provider lets 80 and 443 in and you forwarded them to this machine yourself, or you already run nginx, Caddy or Traefik in front of your apps.',
    advTitle: 'Advanced setup',
    advQ: 'How does HTTPS reach Telinha?',
    advPorts: 'I opened ports 80 and 443 on my router to this machine',
    advPortsDesc: 'Telinha gets the certificate over them, as on a VPS',
    advPortsPreview:
      'Your router forwards TCP 80 and 443 to this machine and your provider does not block them. Telinha will not ask the router for them: keep them forwarded yourself.',
    advProxy: 'My own reverse proxy',
    advProxyDesc: 'It terminates HTTPS and forwards to Telinha',
    advProxyPreview:
      'Your proxy terminates HTTPS and forwards everything to http://127.0.0.1:{port}, WebSockets included.',
    advAddressTitle: 'Address',
    advAddressQ: 'Which address will people open?',
    advAddressNote: 'Telinha will not ask the router for 80 and 443: keep them forwarded yourself.',

    // address: the choices a VPS lists (the advanced home list is its first two)
    choiceDomain: 'My own domain',
    choiceDomainDesc: 'e.g. telinha.example.com, pointed at this machine',
    choiceDomainPreview:
      "Create an A record for your domain pointing at {ip}.\n\nTelinha gets its certificate from Let's Encrypt over ports 80 and 443.",
    choiceDomainPreviewNoIp:
      "Create an A record for your domain pointing at the public IP of this machine.\n\nTelinha gets its certificate from Let's Encrypt over ports 80 and 443.",
    choiceDuck: 'A free DuckDNS address',
    choiceDuckDesc: '<name>.duckdns.org, follows a changing IP',
    choiceDuckPreview:
      'A free subdomain from duckdns.org. Telinha keeps it pointing at this machine and gets the certificate over ports 80 and 443.',
    vpsAddressTitle: 'How will people reach Telinha?',
    vpsAddressQ: 'Pick the web address Telinha uses.',
    vpsSslip: 'No domain: sslip.io',
    vpsSslipDesc: "A name made from the server's fixed IP",
    vpsSslipPreview:
      "sslip.io is a shared domain: Let's Encrypt may refuse certificates when too many are issued for it in a week. A domain of your own (or DuckDNS) is more reliable.",
    vpsSslipPreviewUrl:
      "Your address: {url}\n\nsslip.io is a shared domain: Let's Encrypt may refuse certificates when too many are issued for it in a week. A domain of your own (or DuckDNS) is more reliable.",
    vpsTunnel: 'Cloudflare Tunnel',
    vpsTunnelDesc: 'Needs a domain on Cloudflare; no web ports to open',
    vpsTunnelPreview: 'Telinha runs cloudflared and Cloudflare handles HTTPS: ports 80 and 443 can stay closed.',
    vpsExternal: 'Advanced: my own reverse proxy',
    vpsExternalDesc: 'It terminates HTTPS and forwards to Telinha',

    // address: the answers
    domainTitle: 'Your domain',
    domainQ: 'Which hostname will people open?',
    domainPlaceholder: 'telinha.example.com',
    domainHint: 'Use a name you control. Its A record must point at {ip} before Telinha can get a certificate.',
    domainHintNoIp:
      'Use a name you control. Its A record must point at the public IP of this network before Telinha can get a certificate.',
    hostBad: 'That is not a hostname like telinha.example.com.',
    dnsChecking: 'Looking up {host}…',
    dnsOk: '{host} points at this network ({ip}).',
    dnsWrong: '{host} points at {now}, not at {ip}: set its A record to {ip} (it can take a few minutes).',
    dnsUnknown: '{host} points at {now}; check that this is the public IP of this network.',
    dnsWrongNone: '{host} does not point anywhere yet: set its A record to {ip} (it can take a few minutes).',
    dnsUnknownNone: '{host} does not point anywhere yet: set its A record to the public IP of this network.',
    duckNameTitle: 'DuckDNS name',
    duckNameQ: 'Your subdomain: the part before .duckdns.org.',
    duckNamePlaceholder: 'my-group',
    duckHelp: 'Open duckdns.org, sign in, add a subdomain, and copy the token shown at the top.',
    duckDomainBad: 'Lowercase letters, digits and - only, e.g. my-group.',
    duckTokenTitle: 'DuckDNS token',
    duckTokenQ: 'Paste the token shown at the top of duckdns.org.',
    duckTokenHint:
      'Telinha uses it to keep {name}.duckdns.org pointing at this network and to prove the name is yours when it gets the HTTPS certificate.',
    duckChecking: 'Updating {name}…',
    duckOk: '{name} now points at {ip}.',
    duckFailed: 'DuckDNS did not accept it: {error}',
    duckKept: 'DuckDNS did not accept the token for {name} yet; the running service keeps trying.',
    httpsPortTitle: 'HTTPS port',
    httpsPortQ: 'Which port will the pages use? (1024-65535)',
    httpsPortHint:
      "Telinha serves HTTPS on a port of its own and gets the certificate from Let's Encrypt through your DuckDNS token: nothing to open on 80 or 443. Change it only if {port} is already used on this machine.",
    httpsPortUrl: 'Your address: https://{name}.duckdns.org:{port}',
    portBad: 'A port is a number from 1 to 65535.',
    httpsPortLow: 'Use a port from 1024 up: home connections usually do not let 80 or 443 in.',
    httpsPortTaken: 'That port is already used by Telinha ({what}).',
    vpsNodeIpTitle: 'Public IPv4',
    vpsNodeIpQ: 'The public IPv4 of this server (setup could not find it).',
    vpsNodeIpPlaceholder: '203.0.113.9',
    ipBad: 'That is not an IPv4 address like 203.0.113.9.',
    tunnelTokenTitle: 'Cloudflare Tunnel token',
    tunnelTokenQ: 'Paste the tunnel token, or the whole install command Cloudflare shows.',
    tunnelHelp:
      'Cloudflare Zero Trust -> Networks -> Tunnels -> Create a tunnel (cloudflared) -> copy the install command it shows\n(pasting the whole command is fine: Telinha keeps the token, the part starting with eyJ).\nThen add a public hostname whose service is http://localhost:{port}.',
    tunnelTokenBad: 'That does not look like a Cloudflare tunnel token (it starts with eyJ).',
    tunnelHostTitle: 'Tunnel hostname',
    tunnelHostQ: 'The public hostname of the tunnel, e.g. telinha.example.com.',
    externalTitle: 'Public address',
    externalQ: 'The address your proxy serves: https://host or https://host:port.',
    externalPlaceholder: 'https://telinha.example.com',
    urlBad: 'Give the address as https://host or https://host:port, without a path.',

    // discord
    discordTokenTitle: 'Discord bot token',
    discordTokenQ: "Paste your bot's token.",
    discordTokenHelp:
      'Your Discord app: discord.com/developers/applications -> New Application, then Bot -> Reset Token and copy it.\nTelinha checks it with Discord right away (it only reads).',
    discordChecking: 'Checking the token with Discord…',
    discordBot: 'Bot: {name} (app id {id})',
    intentsOff: 'Server Members Intent and Presence Intent are off: Telinha switches them on during the install.',
    discordTokenRejected: 'Discord rejected the token; copy it again and paste it here.',
    discordUnreachable: 'Discord could not be reached: {error}',
    discordOffline: 'Discord is not contacted (--no-discord-check): ids are typed by hand and nothing is verified.',
    clientIdTitle: 'Application id',
    clientIdQ: 'OAuth2 page -> Client ID.',
    idBad: 'A Discord id is 17 to 20 digits.',
    clientSecretTitle: 'Client secret',
    clientSecretQ: 'Paste the client secret.',
    secretHelp: 'OAuth2 page -> Client Secret -> Reset Secret, and copy it.',
    secretChecking: 'Checking the client secret…',
    secretOk: 'Client secret accepted.',
    secretRejected: 'Discord rejected the client secret.',
    secretUnchecked: 'Could not check the client secret ({error}); keeping it.',
    redirectTitle: 'Login redirect',
    redirectQ: 'Discord cannot add the login redirect through its API: add it by hand.',
    redirectHelp: 'On the OAuth2 page: Redirects -> Add Redirect, paste this, then Save Changes:',
    redirectCheck: 'I added it: check again',
    redirectSkip: 'Skip for now',
    redirectChecking: "Reading the app's redirects…",
    redirectOk: 'Redirect URI is registered.',
    redirectMissing: 'Not there yet (did you press Save Changes?).',
    redirectSkipped: 'Login will fail until {uri} is a redirect of the app (telinha doctor checks it).',
    guildTitle: 'Which server?',
    guildQ: 'Which Discord server is Telinha for?',
    guildOther: 'Another server (add the bot)',
    guildsLoading: 'Loading the servers the bot is in…',
    guildNone: 'The bot is not in any server yet.',
    guildMissing: 'The bot is not in server {id}.',
    inviteHelp: 'Add the bot to your server with this link (you need Manage Server there):',
    guildIdQ: 'Server (guild) id.',
    roleTitle: 'Who may enter the rooms?',
    roleQ: 'Pick the role whose members may enter the rooms.',
    roleHelp: 'Members with this role may enter the rooms; @everyone lets the whole server in.',
    roleEveryone: 'Everyone in the server (@everyone)',
    rolesLoading: "Loading the server's roles…",
    roleIdQ: 'Role id.',
    channelsTitle: 'Where does the command work?',
    channelsQ: 'Pick one or more text channels.',
    channelsHelp: 'The slash command works only in these channels.',
    channelsMin: 'Pick at least one channel.',
    channelsLoading: "Loading the server's channels…",
    channelsNone: 'The bot sees no text channel in {guild}; give it access to one, then check again.',
    channelIdsQ: 'Channel ids, comma separated.',
    commandTitle: 'Command name',
    commandQ: 'The slash command people type in Discord.',
    commandHint:
      'People type /{name} in one of the chosen channels to open a room. Lowercase letters, digits, - or _, at most 32.',
    commandBad: 'Lowercase letters, digits, - or _, at most 32.',
    groupTitle: 'Group name',
    groupQ: "Shown in the pages and in the command's replies.",
    groupHint: "Leave it empty to use the role's name, or the Discord server's name when everyone may join ({name}).",
    groupDefault: "the role's name, or the Discord server's",

    // ports
    // media
    mediaChoiceTitle: 'Video',
    mediaChoiceQ: 'Where does the video go through?',
    mediaChoiceHelp: 'LiveKit carries the screen shares. It runs on this machine unless you use LiveKit Cloud.',
    mediaSelf: 'This computer',
    mediaSelfDesc: 'Recommended: free, no limits',
    mediaSelfPreview:
      'LiveKit runs next to Telinha and two media ports (TCP and UDP) must reach this machine from the internet.',
    mediaCloud: 'LiveKit Cloud',
    mediaCloudDesc: 'No media ports to open; free plan has limits',
    mediaCloudPreview:
      'A free LiveKit Cloud project carries the video: no media ports to open here. The free plan has 5,000 participant-minutes and 50 GB a month, 100 people at once.',
    cloudUrlTitle: 'LiveKit Cloud project',
    cloudUrlQ: 'The project URL (Settings → Project):',
    cloudUrlHelp: 'Make a free project on cloud.livekit.io; its URL looks like wss://my-project-abc123.livekit.cloud.',
    cloudAutoCreate: 'Turn automatic room creation off in the project settings: Telinha creates its rooms itself.',
    cloudUrlBad: 'Paste the project URL: wss://<project>.livekit.cloud',
    cloudKeyTitle: 'LiveKit Cloud key',
    cloudKeyQ: 'The API key (Settings → Keys):',
    cloudKeyHelp: 'Settings → Keys → Create key on cloud.livekit.io shows the key and its secret once.',
    cloudSecretTitle: 'LiveKit Cloud secret',
    cloudSecretQ: 'The secret of that key:',
    turnTitle: 'Strict networks',
    turnQ: 'Also serve video through port 443 for strict networks?',
    turnHelp:
      'Some offices, schools and mobile carriers let browsers reach port 443 only. With this on, their video relays through turn.<your address>:443 (TURN over TLS), which looks like any HTTPS site.',
    turnOn: 'Yes',
    turnOnDesc: 'Recommended',
    turnOff: 'No',
    turnOffDesc: 'People on those networks see no video',
    mediaCgnat:
      'This network is behind carrier-grade NAT (CGNAT): the internet cannot reach its media ports, so LiveKit Cloud is picked for you.',
    turnDnsHint: 'First add a DNS record: {host} → {ip} (A record, DNS only). Yes then checks that it resolves.',
    turnDnsHintNoIp:
      "First add a DNS record: {host} → this server's public IP (A record, DNS only). Yes then checks that it resolves.",
    turnAutoHint: '{host} already points at this server: nothing to add.',
    turnChecking: 'Looking up {host}…',
    turnKept: '{host} does not resolve to this server yet; the turn check of telinha doctor says when it does.',
    actionTurnCheck: 'I added it: check again',
    actionTurnKeep: 'Keep it on anyway',
    cgnatCloud:
      "The router's external IP is a carrier-grade NAT address (100.64.0.0/10): LiveKit Cloud carries the video, but the HTTPS port still cannot reach this network. A Cloudflare Tunnel needs no open port.",

    mediaTitle: 'Media ports',
    mediaQ: 'Screen sharing goes over one TCP and one UDP port.',
    mediaKeep: 'Keep TCP {tcp} and UDP {udp}',
    mediaKeepDesc: 'The usual choice',
    mediaChange: 'Change them',
    mediaChangeDesc: 'Only if something else on this machine uses them',
    mediaHelp: 'Both must reach this machine from the internet.',
    vpsFirewall:
      "Open these ports in your provider's firewall (security group / security list) and in this machine's own firewall: {ports}",
    vpsFwUfw: 'With ufw: {cmd}',
    vpsFwFirewalld: 'With firewalld: {cmd}',
    winFirewall: 'Telinha adds Windows Firewall rules for these ports during the install.',
    mediaTcpTitle: 'TCP port',
    mediaTcpQ: 'The TCP port for the media (7881 by default).',
    mediaUdpTitle: 'UDP port',
    mediaUdpQ: 'The UDP port for the media (7882 by default).',
    mediaPortIsHttps: 'That is the HTTPS port; pick another.',
    mediaBusy: '{proto} {port} is in use on this machine (fine if it is Telinha itself).',
    sysctlTitle: 'Ports below 1024',
    sysctlQ: 'Allow them with one sudo command during the install?',
    sysctlExplain:
      'Ports {ports} are below 1024: Linux lets only root bind them unless one setting changes. One sudo command allows ports from 80 up for every user (it survives updates).',
    sysctlSudo: 'Yes: run it with sudo during the install',
    sysctlSudoDesc: 'You type your password once',
    sysctlManual: 'No: show me the command for later',
    sysctlManualDesc: 'Telinha cannot use those ports until it runs',
    upnpTitle: 'Ask the router?',
    upnpQ: 'Let Telinha ask the router to open the ports it needs (UPnP / NAT-PMP)?',
    upnpAuto: 'Yes, ask the router',
    upnpAutoDesc: 'Works on most home routers; telinha doctor shows the result',
    upnpOff: 'No, I forward them myself',
    upnpOffDesc: 'Setup lists the ports to forward',
    upnpHelp: 'The media ports must reach this machine from the internet.',
    upnpHelpHttps: 'The media ports and TCP {port} must reach this machine from the internet.',
    advUpnpHelp: 'The media ports must reach this machine from the internet (80 and 443 stay forwarded by hand).',
    upnpPorts: 'Ports to forward:',
    routerNone: 'No router answered UPnP, NAT-PMP or PCP.',
    cgnat:
      "The router's external IP is a carrier-grade NAT address (100.64.0.0/10): nothing from the internet can reach this network. Choose LiveKit Cloud in the Video step (with a Cloudflare Tunnel nothing needs to reach it), ask the ISP for a public IP, or run Telinha on a VPS.",
    doubleNat:
      "The router's external IP is private: there is a second router in front of it (double NAT). Forward the ports on that one too, or put this router in bridge mode.",

    // updates
    updatesTitle: 'Updates',
    updatesQ: 'Keep Telinha updated automatically?',
    updatesHelp: 'New stable releases install themselves once no room is open.',
    updatesOn: 'Yes, update automatically',
    updatesOnDesc: 'Recommended',
    updatesOff: 'No, I run telinha update myself',
    updatesOffDesc: 'Telinha stays on this version until then',

    // tray
    trayTitle: 'Tray icon',
    trayQ: 'Show a Telinha icon next to the clock?',
    trayHelp:
      'The icon shows whether Telinha is running, opens the room page and the log, and starts, stops or updates it. telinha tray start shows it any time.',
    trayYes: 'Yes, show the icon',
    trayYesDesc: 'Recommended',
    trayNo: 'No icon',
    trayNoDesc: 'Telinha runs the same without it',
    trayAutoTitle: 'Start with Windows',
    trayAutoQ: 'Start the icon when you sign in to Windows?',
    trayAutoHelp:
      'Telinha itself starts with Windows either way; this is only the icon. Its menu turns it on or off later.',
    trayAutoNo: 'No',
    trayAutoNoDesc: 'telinha tray start shows it when you want it',
    trayAutoYes: 'Yes, at every sign-in',
    trayAutoYesDesc: 'The icon is there after every restart',

    // sidebar summaries and review
    sumHome: 'A computer at home',
    sumVps: 'Rented server (VPS)',
    sumTunnel: 'Cloudflare Tunnel',
    sumDuckHome: 'DuckDNS :{port}',
    sumDuck: 'DuckDNS',
    sumSslip: 'sslip.io',
    sumProxy: 'Own proxy',
    sumOn: 'automatic',
    sumOff: 'manual',
    sumMediaSelf: 'this computer',
    sumMediaCloud: 'LiveKit Cloud',
    sumTurn: 'this computer, 443 too',
    sumTrayOn: 'icon',
    sumTrayAuto: 'icon, at sign-in',
    sumTrayOff: 'no icon',
    reviewWeb: 'Web address',
    reviewSet: 'set',
    reviewKept: 'kept',
    reviewHttpPort: 'HTTP port',
    reviewHttpsPort: 'HTTPS port',
    reviewNodeIp: 'LiveKit node IP',

    // non-interactive runs
    missing: 'missing in non-interactive mode: {list}',
    missingSecret: '{env} (environment) or {flag} <path|->',
    badFlagValue: '{flag}: {value} is not valid (want {allowed})',
    idAllowed: 'a Discord id: 17-20 digits',
    homeNeedsAdvanced:
      'at home Telinha never relies on ports 80/443: use --duckdns-domain (HTTPS on a high port), --ingress tunnel, or --advanced to confirm you opened 80 and 443 yourself (or run your own proxy); on a rented server pass --host vps',
  },
  {
    stepWhere: 'Onde',
    stepAddress: 'Endereço',
    stepDiscord: 'Discord',
    stepMedia: 'Vídeo',
    stepPorts: 'Portas',
    stepUpdates: 'Atualizações',
    stepTray: 'Ícone',
    stepReview: 'Revisão',
    stepInstall: 'Instalação',
    badge: '{step} · Passo {n} de {total}',
    required: 'Isto não pode ficar vazio.',
    notOffered: 'Escolha uma das opções.',
    locked: 'Responda os passos anteriores primeiro',
    actionRetry: 'Tentar de novo',
    actionQuit: 'Sair do setup',
    actionOpen: 'Abrir o link no navegador',
    actionAdded: 'Adicionei o bot: verificar de novo',
    actionCheck: 'Verificar de novo',
    actionTypeAgain: 'Digitar o token de novo',
    actionKeep: 'Manter assim mesmo (o serviço tenta de novo)',
    openFailed: 'Não deu pra abrir um navegador; abra o link à mão.',

    hostChecking: 'Olhando esta máquina e a rede dela…',
    hostLineIp: 'Esta máquina: {os}, {arch}, IP público {ip}.',
    hostLineNoIp: 'Esta máquina: {os}, {arch}, IP público desconhecido (sem internet?).',
    hostRouter: 'Roteador: {router}.',

    langTitle: 'Language / Idioma',
    langQ: 'O idioma deste setup e do comando telinha.',
    langEn: 'English',
    langPt: 'Português (Brasil)',
    hostingTitle: 'Onde a Telinha vai rodar?',
    hostingQ: 'Escolha a máquina que fica ligada e hospeda as salas.',
    hostingHome: 'Um computador em casa',
    hostingHomeDesc: 'Seu PC ou um servidor caseiro, atrás do roteador da sua internet',
    hostingHomePreview:
      'Bom pra um grupo de amigos: a Telinha roda numa máquina que você já tem.\n\nA internet de casa em geral não deixa as portas web 80 e 443 entrarem, então a Telinha não conta com elas. Em seguida você escolhe como o pessoal chega nesta máquina: um Cloudflare Tunnel (se você tem um domínio na Cloudflare) ou um endereço grátis do DuckDNS com HTTPS na porta 8443.',
    vpsHosting: 'Um servidor alugado (VPS)',
    vpsHostingDesc: 'Hetzner, DigitalOcean, Oracle Cloud e parecidos: tem IP público próprio',
    vpsHostingPreview:
      'Uma VPS tem IP público e as portas web 80 e 443 chegam nela, então a Telinha pega o certificado HTTPS do jeito de sempre.\n\nO firewall do provedor precisa deixar as portas da Telinha passarem; o setup lista quais são.',

    homeCfTitle: 'Você tem um domínio na Cloudflare?',
    homeCfQ:
      'A internet de casa em geral não deixa as portas web 80 e 443 entrarem, então a Telinha não conta com elas.',
    homeCfYes: 'Sim: usar um Cloudflare Tunnel',
    homeCfYesDesc: 'Seu próprio endereço; nada pra abrir pras páginas',
    homeCfYesPreview:
      'A Telinha roda o cloudflared e a Cloudflare encaminha https://seu.dominio pra ele.\n\nNada muda no roteador pras páginas. O compartilhamento de tela em si ainda precisa das portas de mídia (num passo mais adiante).',
    homeCfNo: 'Não: usar um endereço grátis do DuckDNS',
    homeCfNoDesc: 'Tipo https://nome.duckdns.org:8443',
    homeCfNoPreview:
      "Você fica com https://<nome>.duckdns.org:8443. O certificado vem do Let's Encrypt pelo seu token do DuckDNS (DNS-01): nada pra abrir na 80 ou na 443.\n\nAlgumas redes rígidas (empresas, escolas) só deixam o navegador chegar na porta 443, então quem estiver nelas não abre os links; um domínio na Cloudflare não tem essa limitação.\n\nVocê precisa de uma conta grátis no duckdns.org e do token dela.",
    advHomeCf: 'Avançado…',
    advHomeCfDesc: 'Eu mesmo abri a 80/443, ou tenho meu próprio proxy reverso',
    advHomeCfPreview:
      'Só se você sabe que a sua operadora deixa a 80 e a 443 entrarem e você mesmo redirecionou elas pra esta máquina, ou se já roda nginx, Caddy ou Traefik na frente dos seus apps.',
    advTitle: 'Configuração avançada',
    advQ: 'Como o HTTPS chega na Telinha?',
    advPorts: 'Eu abri as portas 80 e 443 no meu roteador pra esta máquina',
    advPortsDesc: 'A Telinha pega o certificado por elas, como numa VPS',
    advPortsPreview:
      'Seu roteador redireciona a TCP 80 e a 443 pra esta máquina e a sua operadora não bloqueia elas. A Telinha não vai pedir elas pro roteador: mantenha o redirecionamento por sua conta.',
    advProxy: 'Meu próprio proxy reverso',
    advProxyDesc: 'Ele termina o HTTPS e repassa pra Telinha',
    advProxyPreview: 'Seu proxy termina o HTTPS e repassa tudo pra http://127.0.0.1:{port}, WebSockets incluídos.',
    advAddressTitle: 'Endereço',
    advAddressQ: 'Qual endereço o pessoal vai abrir?',
    advAddressNote: 'A Telinha não vai pedir a 80 e a 443 pro roteador: mantenha o redirecionamento por sua conta.',

    choiceDomain: 'Meu próprio domínio',
    choiceDomainDesc: 'ex.: telinha.exemplo.com.br, apontado pra esta máquina',
    choiceDomainPreview:
      "Crie um registro A do seu domínio apontando pra {ip}.\n\nA Telinha pega o certificado do Let's Encrypt pelas portas 80 e 443.",
    choiceDomainPreviewNoIp:
      "Crie um registro A do seu domínio apontando pro IP público desta máquina.\n\nA Telinha pega o certificado do Let's Encrypt pelas portas 80 e 443.",
    choiceDuck: 'Um endereço grátis do DuckDNS',
    choiceDuckDesc: '<nome>.duckdns.org, acompanha IP que muda',
    choiceDuckPreview:
      'Um subdomínio grátis do duckdns.org. A Telinha mantém ele apontando pra esta máquina e pega o certificado pelas portas 80 e 443.',
    vpsAddressTitle: 'Como o pessoal vai chegar na Telinha?',
    vpsAddressQ: 'Escolha o endereço web que a Telinha usa.',
    vpsSslip: 'Sem domínio: sslip.io',
    vpsSslipDesc: 'Um nome feito a partir do IP fixo do servidor',
    vpsSslipPreview:
      "sslip.io é um domínio compartilhado: o Let's Encrypt pode recusar certificados quando muitos são emitidos pra ele na semana. Um domínio seu (ou o DuckDNS) é mais confiável.",
    vpsSslipPreviewUrl:
      "Seu endereço: {url}\n\nsslip.io é um domínio compartilhado: o Let's Encrypt pode recusar certificados quando muitos são emitidos pra ele na semana. Um domínio seu (ou o DuckDNS) é mais confiável.",
    vpsTunnel: 'Cloudflare Tunnel',
    vpsTunnelDesc: 'Precisa de um domínio na Cloudflare; sem portas web pra abrir',
    vpsTunnelPreview:
      'A Telinha roda o cloudflared e a Cloudflare cuida do HTTPS: as portas 80 e 443 podem ficar fechadas.',
    vpsExternal: 'Avançado: meu próprio proxy reverso',
    vpsExternalDesc: 'Ele termina o HTTPS e repassa pra Telinha',

    domainTitle: 'Seu domínio',
    domainQ: 'Qual nome de host o pessoal vai abrir?',
    domainPlaceholder: 'telinha.exemplo.com.br',
    domainHint:
      'Use um nome que você controla. O registro A dele precisa apontar pra {ip} antes da Telinha conseguir um certificado.',
    domainHintNoIp:
      'Use um nome que você controla. O registro A dele precisa apontar pro IP público desta rede antes da Telinha conseguir um certificado.',
    hostBad: 'Isso não é um nome de host como telinha.exemplo.com.br.',
    dnsChecking: 'Consultando {host}…',
    dnsOk: '{host} aponta pra esta rede ({ip}).',
    dnsWrong: '{host} aponta pra {now}, não pra {ip}: ajuste o registro A pra {ip} (pode levar alguns minutos).',
    dnsUnknown: '{host} aponta pra {now}; confira se esse é o IP público desta rede.',
    dnsWrongNone: '{host} ainda não aponta pra lugar nenhum: ajuste o registro A pra {ip} (pode levar alguns minutos).',
    dnsUnknownNone: '{host} ainda não aponta pra lugar nenhum: ajuste o registro A pro IP público desta rede.',
    duckNameTitle: 'Nome no DuckDNS',
    duckNameQ: 'Seu subdomínio: a parte antes de .duckdns.org.',
    duckNamePlaceholder: 'meu-grupo',
    duckHelp: 'Abra o duckdns.org, entre, adicione um subdomínio e copie o token mostrado no topo.',
    duckDomainBad: 'Só letras minúsculas, dígitos e -, ex.: meu-grupo.',
    duckTokenTitle: 'Token do DuckDNS',
    duckTokenQ: 'Cole o token mostrado no topo do duckdns.org.',
    duckTokenHint:
      'A Telinha usa ele pra manter {name}.duckdns.org apontando pra esta rede e pra provar que o nome é seu na hora de pegar o certificado HTTPS.',
    duckChecking: 'Atualizando {name}…',
    duckOk: '{name} agora aponta pra {ip}.',
    duckFailed: 'O DuckDNS não aceitou: {error}',
    duckKept: 'O DuckDNS ainda não aceitou o token de {name}; o serviço rodando continua tentando.',
    httpsPortTitle: 'Porta HTTPS',
    httpsPortQ: 'Qual porta as páginas vão usar? (1024-65535)',
    httpsPortHint:
      "A Telinha serve HTTPS numa porta própria e pega o certificado do Let's Encrypt pelo seu token do DuckDNS: nada pra abrir na 80 ou na 443. Só mude se a {port} já estiver em uso nesta máquina.",
    httpsPortUrl: 'Seu endereço: https://{name}.duckdns.org:{port}',
    portBad: 'Porta é um número de 1 a 65535.',
    httpsPortLow: 'Use uma porta a partir da 1024: a internet de casa em geral não deixa a 80 nem a 443 entrarem.',
    httpsPortTaken: 'Essa porta já é usada pela Telinha ({what}).',
    vpsNodeIpTitle: 'IPv4 público',
    vpsNodeIpQ: 'O IPv4 público deste servidor (o setup não conseguiu descobrir).',
    vpsNodeIpPlaceholder: '203.0.113.9',
    ipBad: 'Isso não é um endereço IPv4 como 203.0.113.9.',
    tunnelTokenTitle: 'Token do Cloudflare Tunnel',
    tunnelTokenQ: 'Cole o token do túnel, ou o comando de instalação inteiro que a Cloudflare mostra.',
    tunnelHelp:
      'Cloudflare Zero Trust -> Networks -> Tunnels -> Create a tunnel (cloudflared) -> copie o comando de instalação mostrado\n(pode colar o comando inteiro: a Telinha fica com o token, a parte que começa com eyJ).\nDepois adicione um public hostname cujo service é http://localhost:{port}.',
    tunnelTokenBad: 'Isso não parece um token de túnel da Cloudflare (ele começa com eyJ).',
    tunnelHostTitle: 'Hostname do túnel',
    tunnelHostQ: 'O hostname público do túnel, ex.: telinha.exemplo.com.br.',
    externalTitle: 'Endereço público',
    externalQ: 'O endereço que o seu proxy serve: https://host ou https://host:porta.',
    externalPlaceholder: 'https://telinha.exemplo.com.br',
    urlBad: 'Informe o endereço como https://host ou https://host:porta, sem caminho.',

    discordTokenTitle: 'Token do bot do Discord',
    discordTokenQ: 'Cole o token do seu bot.',
    discordTokenHelp:
      'Seu app do Discord: discord.com/developers/applications -> New Application, depois Bot -> Reset Token e copie.\nA Telinha confere ele com o Discord na hora (só leitura).',
    discordChecking: 'Conferindo o token com o Discord…',
    discordBot: 'Bot: {name} (app id {id})',
    intentsOff:
      'Server Members Intent e Presence Intent estão desligados: a Telinha liga os dois durante a instalação.',
    discordTokenRejected: 'O Discord recusou o token; copie de novo e cole aqui.',
    discordUnreachable: 'Não deu pra falar com o Discord: {error}',
    discordOffline: 'O Discord não é consultado (--no-discord-check): os ids são digitados à mão e nada é verificado.',
    clientIdTitle: 'Id da aplicação',
    clientIdQ: 'Página OAuth2 -> Client ID.',
    idBad: 'Um id do Discord tem de 17 a 20 dígitos.',
    clientSecretTitle: 'Client secret',
    clientSecretQ: 'Cole o client secret.',
    secretHelp: 'Página OAuth2 -> Client Secret -> Reset Secret, e copie.',
    secretChecking: 'Conferindo o client secret…',
    secretOk: 'Client secret aceito.',
    secretRejected: 'O Discord recusou o client secret.',
    secretUnchecked: 'Não deu pra verificar o client secret ({error}); mantendo.',
    redirectTitle: 'Redirect do login',
    redirectQ: 'O Discord não deixa adicionar o redirect de login pela API: adicione à mão.',
    redirectHelp: 'Na página OAuth2: Redirects -> Add Redirect, cole isto e clique em Save Changes:',
    redirectCheck: 'Adicionei: verificar de novo',
    redirectSkip: 'Pular por enquanto',
    redirectChecking: 'Lendo os redirects do app…',
    redirectOk: 'O redirect URI está cadastrado.',
    redirectMissing: 'Ainda não está lá (clicou em Save Changes?).',
    redirectSkipped: 'O login vai falhar até {uri} ser um redirect do app (o telinha doctor verifica).',
    guildTitle: 'Qual servidor?',
    guildQ: 'A Telinha é pra qual servidor do Discord?',
    guildOther: 'Outro servidor (adicionar o bot)',
    guildsLoading: 'Carregando os servidores em que o bot está…',
    guildNone: 'O bot ainda não está em nenhum servidor.',
    guildMissing: 'O bot não está no servidor {id}.',
    inviteHelp: 'Adicione o bot ao seu servidor com este link (precisa de Gerenciar Servidor lá):',
    guildIdQ: 'Id do servidor (guild).',
    roleTitle: 'Quem pode entrar nas salas?',
    roleQ: 'Escolha o cargo cujos membros podem entrar nas salas.',
    roleHelp: 'Quem tem este cargo pode entrar nas salas; @everyone deixa o servidor inteiro entrar.',
    roleEveryone: 'Todo mundo do servidor (@everyone)',
    rolesLoading: 'Carregando os cargos do servidor…',
    roleIdQ: 'Id do cargo.',
    channelsTitle: 'Onde o comando funciona?',
    channelsQ: 'Escolha um ou mais canais de texto.',
    channelsHelp: 'O comando de barra só funciona nestes canais.',
    channelsMin: 'Escolha pelo menos um canal.',
    channelsLoading: 'Carregando os canais do servidor…',
    channelsNone: 'O bot não vê nenhum canal de texto em {guild}; dê acesso a um e verifique de novo.',
    channelIdsQ: 'Ids dos canais, separados por vírgula.',
    commandTitle: 'Nome do comando',
    commandQ: 'O comando de barra que o pessoal digita no Discord.',
    commandHint:
      'O pessoal digita /{name} num dos canais escolhidos pra abrir uma sala. Letras minúsculas, dígitos, - ou _, no máximo 32.',
    commandBad: 'Letras minúsculas, dígitos, - ou _, no máximo 32.',
    groupTitle: 'Nome do grupo',
    groupQ: 'Aparece nas páginas e nas respostas do comando.',
    groupHint:
      'Deixe vazio pra usar o nome do cargo, ou o do servidor do Discord quando todo mundo pode entrar ({name}).',
    groupDefault: 'o nome do cargo, ou o do servidor do Discord',

    // media
    mediaChoiceTitle: 'Vídeo',
    mediaChoiceQ: 'Por onde passa o vídeo?',
    mediaChoiceHelp:
      'O LiveKit leva os compartilhamentos de tela. Ele roda nesta máquina, a não ser que você use o LiveKit Cloud.',
    mediaSelf: 'Este computador',
    mediaSelfDesc: 'Recomendado: grátis, sem limites',
    mediaSelfPreview:
      'O LiveKit roda junto da Telinha e duas portas de mídia (TCP e UDP) precisam chegar nesta máquina vindas da internet.',
    mediaCloud: 'LiveKit Cloud',
    mediaCloudDesc: 'Sem portas de mídia pra abrir; o plano grátis tem limites',
    mediaCloudPreview:
      'Um projeto grátis no LiveKit Cloud leva o vídeo: nenhuma porta de mídia pra abrir aqui. O plano grátis tem 5.000 minutos de participante e 50 GB por mês, 100 pessoas ao mesmo tempo.',
    cloudUrlTitle: 'Projeto no LiveKit Cloud',
    cloudUrlQ: 'A URL do projeto (Settings → Project):',
    cloudUrlHelp:
      'Crie um projeto grátis em cloud.livekit.io; a URL dele é tipo wss://meu-projeto-abc123.livekit.cloud.',
    cloudAutoCreate:
      'Desligue a criação automática de salas nas configurações do projeto: a Telinha cria as salas dela.',
    cloudUrlBad: 'Cole a URL do projeto: wss://<projeto>.livekit.cloud',
    cloudKeyTitle: 'Chave do LiveKit Cloud',
    cloudKeyQ: 'A chave de API (Settings → Keys):',
    cloudKeyHelp: 'Settings → Keys → Create key em cloud.livekit.io mostra a chave e o segredo dela uma vez.',
    cloudSecretTitle: 'Segredo do LiveKit Cloud',
    cloudSecretQ: 'O segredo dessa chave:',
    turnTitle: 'Redes rígidas',
    turnQ: 'Também passar o vídeo pela porta 443 para redes rígidas?',
    turnHelp:
      'Algumas empresas, escolas e operadoras de celular só deixam o navegador chegar na porta 443. Com isto ligado, o vídeo dessas pessoas passa por turn.<seu endereço>:443 (TURN sobre TLS), que parece um site HTTPS qualquer.',
    turnOn: 'Sim',
    turnOnDesc: 'Recomendado',
    turnOff: 'Não',
    turnOffDesc: 'Quem está nessas redes fica sem vídeo',
    mediaCgnat:
      'Esta rede está atrás de CGNAT da operadora: a internet não chega nas portas de mídia dela, então o LiveKit Cloud já vem escolhido.',
    turnDnsHint: 'Antes crie um registro DNS: {host} → {ip} (registro A, só DNS). O sim então confere se ele resolve.',
    turnDnsHintNoIp:
      'Antes crie um registro DNS: {host} → o IP público deste servidor (registro A, só DNS). O sim então confere se ele resolve.',
    turnAutoHint: '{host} já aponta pra este servidor: nada a criar.',
    turnChecking: 'Consultando {host}…',
    turnKept: '{host} ainda não resolve pra este servidor; a verificação turn do telinha doctor avisa quando resolver.',
    actionTurnCheck: 'Criei: verificar de novo',
    actionTurnKeep: 'Manter ligado assim mesmo',
    cgnatCloud:
      'O IP externo do roteador é de CGNAT da operadora (100.64.0.0/10): o LiveKit Cloud leva o vídeo, mas a porta HTTPS ainda não chega nesta rede. Um Cloudflare Tunnel não precisa de porta aberta.',

    mediaTitle: 'Portas de mídia',
    mediaQ: 'O compartilhamento de tela passa por uma porta TCP e uma UDP.',
    mediaKeep: 'Manter TCP {tcp} e UDP {udp}',
    mediaKeepDesc: 'O normal',
    mediaChange: 'Mudar',
    mediaChangeDesc: 'Só se outra coisa nesta máquina usa elas',
    mediaHelp: 'As duas precisam chegar nesta máquina vindas da internet.',
    vpsFirewall:
      'Libere estas portas no firewall do provedor (security group / security list) e no firewall desta máquina: {ports}',
    vpsFwUfw: 'Com ufw: {cmd}',
    vpsFwFirewalld: 'Com firewalld: {cmd}',
    winFirewall: 'A Telinha adiciona regras no Firewall do Windows pra estas portas durante a instalação.',
    mediaTcpTitle: 'Porta TCP',
    mediaTcpQ: 'A porta TCP da mídia (7881 por padrão).',
    mediaUdpTitle: 'Porta UDP',
    mediaUdpQ: 'A porta UDP da mídia (7882 por padrão).',
    mediaPortIsHttps: 'Essa é a porta HTTPS; escolha outra.',
    mediaBusy: '{proto} {port} está em uso nesta máquina (tudo bem se for a própria Telinha).',
    sysctlTitle: 'Portas abaixo de 1024',
    sysctlQ: 'Liberar elas com um comando sudo durante a instalação?',
    sysctlExplain:
      'As portas {ports} são menores que 1024: o Linux só deixa o root usar elas, a menos que um ajuste mude. Um comando sudo libera as portas a partir da 80 pra todo usuário (vale depois das atualizações).',
    sysctlSudo: 'Sim: rodar com sudo durante a instalação',
    sysctlSudoDesc: 'Você digita sua senha uma vez',
    sysctlManual: 'Não: me mostre o comando pra depois',
    sysctlManualDesc: 'A Telinha não consegue usar essas portas até ele rodar',
    upnpTitle: 'Pedir pro roteador?',
    upnpQ: 'Deixar a Telinha pedir pro roteador abrir as portas que ela precisa (UPnP / NAT-PMP)?',
    upnpAuto: 'Sim, pedir pro roteador',
    upnpAutoDesc: 'Funciona na maioria dos roteadores de casa; o telinha doctor mostra o resultado',
    upnpOff: 'Não, eu mesmo redireciono',
    upnpOffDesc: 'O setup lista as portas pra redirecionar',
    upnpHelp: 'As portas de mídia precisam chegar nesta máquina vindas da internet.',
    upnpHelpHttps: 'As portas de mídia e a TCP {port} precisam chegar nesta máquina vindas da internet.',
    advUpnpHelp:
      'As portas de mídia precisam chegar nesta máquina vindas da internet (a 80 e a 443 seguem redirecionadas na mão).',
    upnpPorts: 'Portas pra redirecionar:',
    routerNone: 'Nenhum roteador respondeu UPnP, NAT-PMP ou PCP.',
    cgnat:
      'O IP externo do roteador é de CGNAT da operadora (100.64.0.0/10): nada da internet chega nesta rede. Escolha o LiveKit Cloud no passo Vídeo (com um Cloudflare Tunnel nada precisa chegar), peça um IP público pra operadora, ou rode a Telinha numa VPS.',
    doubleNat:
      'O IP externo do roteador é privado: tem um segundo roteador na frente (NAT duplo). Redirecione as portas nele também, ou coloque este roteador em modo bridge.',

    updatesTitle: 'Atualizações',
    updatesQ: 'Manter a Telinha atualizada automaticamente?',
    updatesHelp: 'Versões estáveis novas se instalam sozinhas quando não tem sala aberta.',
    updatesOn: 'Sim, atualizar automaticamente',
    updatesOnDesc: 'Recomendado',
    updatesOff: 'Não, eu rodo o telinha update',
    updatesOffDesc: 'A Telinha fica nesta versão até lá',

    // tray
    trayTitle: 'Ícone na bandeja',
    trayQ: 'Mostrar um ícone da Telinha ao lado do relógio?',
    trayHelp:
      'O ícone mostra se a Telinha está rodando, abre a página da sala e o log, e inicia, para ou atualiza ela. O telinha tray start mostra ele a qualquer hora.',
    trayYes: 'Sim, mostrar o ícone',
    trayYesDesc: 'Recomendado',
    trayNo: 'Sem ícone',
    trayNoDesc: 'A Telinha roda igual sem ele',
    trayAutoTitle: 'Iniciar com o Windows',
    trayAutoQ: 'Iniciar o ícone quando você entrar no Windows?',
    trayAutoHelp:
      'A Telinha em si inicia com o Windows de qualquer jeito; isto é só o ícone. O menu dele liga ou desliga depois.',
    trayAutoNo: 'Não',
    trayAutoNoDesc: 'O telinha tray start mostra ele quando você quiser',
    trayAutoYes: 'Sim, a cada entrada',
    trayAutoYesDesc: 'O ícone está lá depois de cada reinício',

    sumHome: 'Computador em casa',
    sumVps: 'Servidor (VPS)',
    sumTunnel: 'Cloudflare Tunnel',
    sumDuckHome: 'DuckDNS :{port}',
    sumDuck: 'DuckDNS',
    sumSslip: 'sslip.io',
    sumProxy: 'Proxy próprio',
    sumOn: 'automáticas',
    sumOff: 'manuais',
    sumMediaSelf: 'este computador',
    sumMediaCloud: 'LiveKit Cloud',
    sumTurn: 'este computador, 443 também',
    sumTrayOn: 'ícone',
    sumTrayAuto: 'ícone, ao entrar',
    sumTrayOff: 'sem ícone',
    reviewWeb: 'Endereço web',
    reviewSet: 'definido',
    reviewKept: 'mantido',
    reviewHttpPort: 'Porta HTTP',
    reviewHttpsPort: 'Porta HTTPS',
    reviewNodeIp: 'IP do LiveKit',

    missing: 'faltando no modo não interativo: {list}',
    missingSecret: '{env} (ambiente) ou {flag} <caminho|->',
    badFlagValue: '{flag}: {value} não vale (esperado {allowed})',
    idAllowed: 'um id do Discord: 17-20 dígitos',
    homeNeedsAdvanced:
      'em casa a Telinha nunca depende das portas 80/443: use --duckdns-domain (HTTPS numa porta alta), --ingress tunnel, ou --advanced pra confirmar que você mesmo abriu a 80 e a 443 (ou tem seu próprio proxy); num servidor alugado passe --host vps',
  },
);

export type QKey = keyof typeof q.en;
