// The wizard's own dictionary (EN + pt-BR): too many keys for cli/strings.ts.
import { defineStrings } from '../strings.ts';

export const t = defineStrings({
  welcome: 'Telinha setup',
  welcomeHelp: 'A few questions and Telinha is ready: where it runs, how people reach it, and your Discord app.\nEvery answer goes to {file}; run telinha setup again to change any of them.',
  failed: 'setup failed: {error}',
  aborted: 'Nothing was written.',
  missing: 'missing in non-interactive mode: {list}',
  missingSecret: '{env} (environment) or {flag} <path|->',
  badFlagValue: '{flag}: {value} is not valid (want {allowed})',
  idAllowed: 'a Discord id: 17-20 digits',
  configInvalid: 'the resulting configuration is invalid: {error}',

  // host
  hostChecking: 'Looking at this machine and its network...',
  hostChecked: 'Machine checked',
  hostLine: 'This machine: {what}.',
  hostPublicIp: 'public IP {ip}',
  hostNoPublicIp: 'public IP unknown (offline?)',
  hostRouter: 'Router: {router}.',
  targetTitle: 'Where Telinha runs',
  targetQ: 'Where does Telinha run?',
  targetHome: 'At home (or an office)',
  targetHomeHint: 'behind a router',
  targetVps: 'A VPS or cloud server',
  targetVpsHint: 'with its own public IP',
  targetCloudflare: 'Behind Cloudflare only',
  targetCloudflareHint: 'no open web ports (Cloudflare Tunnel)',

  // ingress and domain
  ingressTitle: 'Address',
  ingressQ: 'How will people reach Telinha?',
  choiceDomain: 'My own domain',
  choiceDomainHint: 'e.g. telinha.example.com',
  choiceDuck: 'DuckDNS',
  choiceDuckHint: 'free name, follows a changing IP',
  choiceSslip: 'No domain: sslip.io',
  choiceSslipHint: 'name made from the static IP',
  choiceTunnel: 'Cloudflare Tunnel',
  choiceTunnelHint: 'no web ports to open; needs a domain on Cloudflare',
  choiceExternal: 'My own reverse proxy',
  choiceExternalHint: 'advanced: it forwards to Telinha',
  portsHelp: 'Telinha gets its HTTPS certificate itself and needs the web ports from the internet.\nAt home that means port forwarding on the router (or UPnP, asked below).',
  portsQ: 'Can ports 80 and 443 from the internet reach this machine?',
  portsRouterHint: 'Your router accepts automatic port forwarding: answer Yes and Telinha opens 80 and 443 for you (asked below).',
  portsBoth: 'Yes, 80 and 443',
  portsOther: 'Only 443, and to another port on this machine',
  portsNeither: 'No (blocked, or used by something else)',
  portsOtherHelp: 'Then forward public 443 to the port below. Without port 80 the certificate is obtained\nthrough 443 itself (TLS-ALPN challenge), so public 443 must reach this machine.',
  portsInternalQ: 'Port on this machine that receives public 443',
  portsNeitherAdvice: 'Without 80/443 the simplest way is a Cloudflare Tunnel: it needs no open web ports.\nPick it below (the media ports still need forwarding).',
  portBad: 'A port is a number from 1 to 65535.',
  domainQ: 'Hostname (e.g. telinha.example.com)',
  hostBad: 'That is not a hostname like telinha.example.com.',
  urlBad: 'Give the address as https://host or https://host:port, without a path.',
  ipBad: 'That is not an IPv4 address like 203.0.113.9.',
  dnsChecking: 'Looking up {host}...',
  dnsOk: '{host} points at this network ({ip}).',
  dnsWrong: '{host} points at {now}, not at {ip}: set its A record to {ip} (it can take a few minutes).',
  dnsUnknown: '{host} points at {now}; check that this is the public IP of this network.',
  dnsNothing: 'nothing yet',
  duckHelp: 'DuckDNS: open duckdns.org, sign in, add a subdomain, and copy the token shown at the top.',
  duckDomainQ: 'DuckDNS subdomain (the part before .duckdns.org)',
  duckDomainBad: 'Lowercase letters, digits and - only, e.g. my-group.',
  duckTokenQ: 'DuckDNS token',
  duckChecking: 'Updating {name}...',
  duckOk: '{name} now points at {ip}.',
  duckFailed: 'DuckDNS did not accept it: {error}',
  duckRetryQ: 'What now?',
  duckRetry: 'Type the token again',
  duckKeepAnyway: 'Keep it anyway (the running service retries)',
  sslipHelp: 'sslip.io is a shared domain: Let\'s Encrypt may refuse certificates when too many are\nissued for it in a week. A domain of your own (or DuckDNS) is more reliable.',
  sslipIpQ: 'Public IPv4 of this server',
  sslipOk: 'Address: {url}',
  tunnelHelp: 'Cloudflare Zero Trust -> Networks -> Tunnels -> Create a tunnel (cloudflared) -> copy the install command it shows\n(pasting the whole command is fine: Telinha keeps the token, the part starting with eyJ).\nThen add a public hostname whose service is http://localhost:{port}.',
  tunnelTokenQ: 'Tunnel token',
  tunnelTokenBad: 'That does not look like a Cloudflare tunnel token (it starts with eyJ).',
  tunnelHostQ: 'Public hostname of the tunnel (e.g. telinha.example.com)',
  externalHelp: 'Your proxy terminates HTTPS and forwards everything to http://127.0.0.1:{port}, WebSockets included.',
  externalUrlQ: 'Public address (https://host)',
  upnpHelp: 'The media ports must reach this machine from the internet in every mode.',
  upnpQ: 'Let Telinha ask the router to open them (UPnP / NAT-PMP)?',

  // media
  mediaTitle: 'Media ports',
  mediaHelp: 'Video goes over TCP {tcp} and UDP {udp}: both must reach this machine from the internet\n(router forwarding or UPnP).',
  mediaChangeQ: 'Change these ports?',
  mediaTcpQ: 'TCP port',
  mediaUdpQ: 'UDP port',
  mediaBusy: '{proto} {port} is in use on this machine (fine if it is Telinha itself).',

  // discord
  discordTitle: 'Discord',
  discordTokenHelp: 'Your Discord app: discord.com/developers/applications -> New Application,\nthen Bot -> Reset Token and copy it.',
  discordTokenQ: 'Bot token',
  discordChecking: 'Checking the token...',
  discordBot: 'Bot: {name} (app id {id})',
  discordTokenRejected: 'Discord rejected the token; paste it again.',
  discordUnreachable: 'Discord could not be reached: {error}',
  discordGiveUp: 'Discord is needed to finish; run telinha setup again later (or use --no-discord-check).',
  discordOffline: 'Discord is not contacted (--no-discord-check): ids are typed by hand and nothing is verified.',
  tryAgain: 'Try again?',
  intentsOk: 'Server Members Intent and Presence Intent are on.',
  intentsOn: 'Switched on Server Members Intent and Presence Intent.',
  intentsApiFailed: 'Could not switch the intents on automatically: {error}',
  intentsManual: 'Bot page -> Privileged Gateway Intents: switch on Server Members Intent and Presence Intent,\nthen Save Changes.',
  intentsGiveUp: 'The intents are still off: the bot cannot log in ("disallowed intents") until they are on.',
  pressEnterDone: 'Press Enter when done',
  secretHelp: 'OAuth2 page -> Client Secret -> Reset Secret, and copy it.',
  secretQ: 'Client secret',
  secretNew: 'Type a new one',
  secretOk: 'Client secret accepted.',
  secretRejected: 'Discord rejected the client secret.',
  secretUnchecked: 'Could not check the client secret ({error}); keeping it.',
  redirectOk: 'Redirect URI is registered.',
  redirectHelp: 'Discord cannot add the login redirect through its API. On the OAuth2 page:\nRedirects -> Add Redirect, paste this, then Save Changes:',
  redirectQ: 'Added it?',
  redirectCheck: 'Yes, check again',
  redirectSkip: 'Skip for now',
  redirectMissing: 'Not there yet (did you press Save Changes?).',
  redirectSkipped: 'Login will fail until {uri} is a redirect of the app (telinha doctor checks it).',
  inviteHelp: 'Add the bot to your server with this link (you need Manage Server there):',
  openBrowser: 'Open it in the browser?',
  openFailed: 'Could not open a browser; open the link by hand.',
  pressEnterInvited: 'Press Enter once the bot is in the server',
  guildNone: 'The bot is not in any server yet.',
  guildMissing: 'The bot is not in server {id}.',
  guildMissingInvite: 'The bot is not in server {id}; add it with {url}',
  guildGiveUp: 'The bot is still not in a server. Add it with {url}, then run telinha setup again.',
  guildOther: 'Another server (add the bot)',
  guildQ: 'Which server is Telinha for?',
  roleHelp: 'Members with this role may enter the rooms.',
  roleQ: 'Role',
  roleEveryone: 'Everyone in the server (@everyone)',
  roleMissing: 'Role {id} does not exist in the server.',
  channelsHelp: 'The slash command works only in these channels.',
  channelsQ: 'Channels',
  channelsNone: 'The bot sees no text channel in {guild}; give it access to one and run setup again.',
  channelMissing: 'Channel {id} is not a text channel the bot can see.',
  commandQ: 'Slash command name',
  commandBad: 'Lowercase letters, digits, - or _, at most 32.',
  groupQ: 'Group name for pages and replies (empty: the server\'s name, {name})',
  clientIdQ: 'Application (client) id',
  clientIdMismatch: '--client-id {given} does not match the token\'s application {id}; using {id}.',
  guildIdQ: 'Server (guild) id',
  roleIdQ: 'Role id',
  channelIdsQ: 'Channel ids (comma separated)',
  idBad: 'A Discord id is 17 to 20 digits.',

  // updates, review, write
  updatesTitle: 'Updates',
  updatesHelp: 'New stable releases install themselves once no room is open.',
  autoUpdateQ: 'Keep Telinha updated automatically?',
  reviewTitle: 'Review',
  reviewQ: 'Write this configuration?',
  reviewWrite: 'Write it',
  reviewRotate: 'Write it with a new cookie secret',
  reviewRotateHint: 'logs everyone out',
  reviewAbort: 'Cancel',
  secretGenerated: '(generated)',
  secretKept: '(kept)',
  secretSet: '(set)',
  written: 'Wrote {file}',
  aclFailed: 'Could not restrict access to the file: {error}',

  // binaries, service
  binsTitle: 'Programs',
  binsChecking: 'Downloading LiveKit, Caddy / cloudflared...',
  binsOk: 'Programs ready in {dir}',
  binsFailed: 'Download failed: {error}. telinha run tries again at start.',
  binsByService: 'The service downloads LiveKit, Caddy / cloudflared itself, as its own user, when it starts.',
  serviceTitle: 'Service',
  serviceNeedsBinary: 'Running from source: no service is installed (the native binary installs one).',
  serviceUnsupported: 'No service manager on this system; start Telinha with telinha run.',
  serviceInstalling: 'Installing the service ({kind})...',
  serviceInstalled: 'Service installed ({kind})',
  serviceFailed: 'Service install failed: {error}',
  serviceManual: 'Install it later: paste this into PowerShell (Windows asks for administrator rights):\n  {cmd}',
  exeCopied: 'Copied the program to {path}',
  pathAdded: 'Added {dir} to your PATH: new terminals know the telinha command.',
  whoamiFailed: 'Could not read the current Windows account (whoami).',
  uacExplain: 'Windows asks for administrator rights once (UAC): to register the background task\nand allow the media ports through the firewall.',
  uacDeclined: 'Administrator rights were not granted; the service is not installed.',
  uacNoResult: 'The elevated install left no result (exit code {code}).',
  stepTask: 'Background task',
  stepFirewall: 'Firewall rules',
  stepStart: 'Start',
  stepSkipped: '{step}: skipped',
  stepHint: 'Still to do by hand: {cmd}',
  lingerWhy: 'Without it Telinha stops whenever you log out of this machine (an SSH session ending counts).',
  sysctlExplain: 'Ports {ports} are below 1024: Linux lets only root bind them unless one setting changes.\nOne sudo command allows ports from 80 up for every user (it survives updates):',
  sysctlQ: 'Run it with sudo now?',
  sysctlOk: 'Ports from 80 up are allowed now.',
  sysctlFailed: 'The setting was not changed.',
  highPortsExplain: 'Alternative: Telinha listens on 8443 and the router forwards public 443 to 8443\n(no port 80; the certificate comes through 443).',
  highPortsQ: 'Switch to port 8443?',
  highPortsOk: 'HTTPS_PORT=8443, HTTP_PORT=0 written; forward public 443 to 8443 on the router.',
  sysctlManual: 'To use 80/443 later: {cmd}',

  // router
  routerTitle: 'Router',
  routerNone: 'No router answered UPnP, NAT-PMP or PCP.',
  routerFound: 'Router {router}, external IP {ip}',
  forwardByHand: 'Forward these ports on the router to this machine: {ports}',
  routerVps: 'Open these ports in your provider\'s firewall (security group / security list) and in this machine\'s own firewall: {ports}',
  routerVpsUfw: 'ufw is installed; if it is active: {cmd}',
  routerVpsFirewalld: 'firewalld is installed; if it is running: {cmd}',
  upnpWillMap: 'Telinha asks the router for {ports} while it runs (telinha doctor shows the result).',
  cgnat: 'The router\'s external IP is a carrier-grade NAT address (100.64.0.0/10): nothing from the internet\ncan reach this network. Ask the ISP for a public IP, or run Telinha on a VPS.',
  doubleNat: 'The router\'s external IP is private: there is a second router in front of it (double NAT).\nForward the ports on that one too, or put this router in bridge mode.',

  // start, doctor, next
  startTitle: 'Start',
  waitingStart: 'Waiting for Telinha to start...',
  restarting: 'Restarting Telinha with the new configuration...',
  running: 'Telinha is running.',
  notAnswering: 'Telinha does not answer yet. Its log says why: {log}\n{telinha} doctor --local checks the rest.',
  certWaiting: 'Waiting for the HTTPS certificate (Let\'s Encrypt, usually under a minute)...',
  certOk: 'HTTPS certificate in place.',
  certPending: 'No HTTPS certificate yet: getting one can take a few minutes. If doctor flags it below, run {telinha} doctor again in a few minutes before changing anything.',
  consoleRestart: 'Telinha runs in a console: restart it there to use the new configuration.',
  startByHand: 'Start it with: {cmd}',
  doctorTitle: 'Checking everything (telinha doctor)',
  doctorProblems: 'Doctor found problems: the lines above say what to fix; {telinha} doctor checks again.',
  doctorFailed: 'Doctor could not run: {error}',
  nextTitle: 'Next steps',
  nextNative: 'Open {url} or type /{command} in one of the chosen Discord channels.\nSettings live in {file}: run {telinha} setup again to change them, {telinha} doctor to check them.',
  nextDocker: 'Start it on the host:  cd /opt/telinha && docker compose up -d\nKeep it updated:       systemctl enable --now telinha-update.timer\nCheck it:              docker exec -it telinha bun server/src/index.ts doctor',
}, {
  welcome: 'Configuração da Telinha',
  welcomeHelp: 'Algumas perguntas e a Telinha fica pronta: onde ela roda, como o pessoal chega nela e o seu app do Discord.\nAs respostas vão pra {file}; rode telinha setup de novo pra mudar qualquer uma.',
  failed: 'o setup falhou: {error}',
  aborted: 'Nada foi gravado.',
  missing: 'faltando no modo não interativo: {list}',
  missingSecret: '{env} (ambiente) ou {flag} <caminho|->',
  badFlagValue: '{flag}: {value} não vale (esperado {allowed})',
  idAllowed: 'um id do Discord: 17-20 dígitos',
  configInvalid: 'a configuração resultante é inválida: {error}',

  hostChecking: 'Olhando esta máquina e a rede dela...',
  hostChecked: 'Máquina verificada',
  hostLine: 'Esta máquina: {what}.',
  hostPublicIp: 'IP público {ip}',
  hostNoPublicIp: 'IP público desconhecido (sem internet?)',
  hostRouter: 'Roteador: {router}.',
  targetTitle: 'Onde a Telinha roda',
  targetQ: 'Onde a Telinha vai rodar?',
  targetHome: 'Em casa (ou num escritório)',
  targetHomeHint: 'atrás de um roteador',
  targetVps: 'Numa VPS ou servidor na nuvem',
  targetVpsHint: 'com IP público próprio',
  targetCloudflare: 'Só atrás da Cloudflare',
  targetCloudflareHint: 'sem portas web abertas (Cloudflare Tunnel)',

  ingressTitle: 'Endereço',
  ingressQ: 'Como o pessoal vai chegar na Telinha?',
  choiceDomain: 'Meu próprio domínio',
  choiceDomainHint: 'ex.: telinha.exemplo.com.br',
  choiceDuck: 'DuckDNS',
  choiceDuckHint: 'nome grátis, acompanha IP que muda',
  choiceSslip: 'Sem domínio: sslip.io',
  choiceSslipHint: 'nome feito a partir do IP fixo',
  choiceTunnel: 'Cloudflare Tunnel',
  choiceTunnelHint: 'sem portas web pra abrir; precisa de um domínio na Cloudflare',
  choiceExternal: 'Meu próprio proxy reverso',
  choiceExternalHint: 'avançado: ele repassa pra Telinha',
  portsHelp: 'A Telinha pega o certificado HTTPS sozinha e precisa das portas web vindas da internet.\nEm casa isso é redirecionamento de portas no roteador (ou UPnP, perguntado abaixo).',
  portsQ: 'As portas 80 e 443 da internet chegam nesta máquina?',
  portsRouterHint: 'Seu roteador aceita redirecionamento automático de portas: responda Sim e a Telinha abre a 80 e a 443 pra você (perguntado abaixo).',
  portsBoth: 'Sim, 80 e 443',
  portsOther: 'Só a 443, e pra outra porta nesta máquina',
  portsNeither: 'Não (bloqueadas, ou usadas por outra coisa)',
  portsOtherHelp: 'Então redirecione a 443 pública pra porta abaixo. Sem a porta 80 o certificado vem\npela própria 443 (desafio TLS-ALPN), então a 443 pública precisa chegar nesta máquina.',
  portsInternalQ: 'Porta nesta máquina que recebe a 443 pública',
  portsNeitherAdvice: 'Sem 80/443 o mais simples é um Cloudflare Tunnel: não precisa de portas web abertas.\nEscolha ele abaixo (as portas de mídia continuam precisando de redirecionamento).',
  portBad: 'Porta é um número de 1 a 65535.',
  domainQ: 'Nome do host (ex.: telinha.exemplo.com.br)',
  hostBad: 'Isso não é um nome de host como telinha.exemplo.com.br.',
  urlBad: 'Informe o endereço como https://host ou https://host:porta, sem caminho.',
  ipBad: 'Isso não é um endereço IPv4 como 203.0.113.9.',
  dnsChecking: 'Consultando {host}...',
  dnsOk: '{host} aponta pra esta rede ({ip}).',
  dnsWrong: '{host} aponta pra {now}, não pra {ip}: ajuste o registro A pra {ip} (pode levar alguns minutos).',
  dnsUnknown: '{host} aponta pra {now}; confira se esse é o IP público desta rede.',
  dnsNothing: 'nada ainda',
  duckHelp: 'DuckDNS: abra duckdns.org, entre, adicione um subdomínio e copie o token mostrado no topo.',
  duckDomainQ: 'Subdomínio DuckDNS (a parte antes de .duckdns.org)',
  duckDomainBad: 'Só letras minúsculas, dígitos e -, ex.: meu-grupo.',
  duckTokenQ: 'Token do DuckDNS',
  duckChecking: 'Atualizando {name}...',
  duckOk: '{name} agora aponta pra {ip}.',
  duckFailed: 'O DuckDNS não aceitou: {error}',
  duckRetryQ: 'E agora?',
  duckRetry: 'Digitar o token de novo',
  duckKeepAnyway: 'Manter assim mesmo (o serviço tenta de novo)',
  sslipHelp: 'sslip.io é um domínio compartilhado: o Let\'s Encrypt pode recusar certificados quando muitos\nsão emitidos pra ele na semana. Um domínio seu (ou o DuckDNS) é mais confiável.',
  sslipIpQ: 'IPv4 público deste servidor',
  sslipOk: 'Endereço: {url}',
  tunnelHelp: 'Cloudflare Zero Trust -> Networks -> Tunnels -> Create a tunnel (cloudflared) -> copie o comando de instalação mostrado\n(pode colar o comando inteiro: a Telinha fica com o token, a parte que começa com eyJ).\nDepois adicione um public hostname cujo service é http://localhost:{port}.',
  tunnelTokenQ: 'Token do túnel',
  tunnelTokenBad: 'Isso não parece um token de túnel da Cloudflare (ele começa com eyJ).',
  tunnelHostQ: 'Hostname público do túnel (ex.: telinha.exemplo.com.br)',
  externalHelp: 'Seu proxy termina o HTTPS e repassa tudo pra http://127.0.0.1:{port}, WebSockets incluídos.',
  externalUrlQ: 'Endereço público (https://host)',
  upnpHelp: 'As portas de mídia precisam chegar nesta máquina vindas da internet em qualquer modo.',
  upnpQ: 'Deixar a Telinha pedir pro roteador abrir elas (UPnP / NAT-PMP)?',

  mediaTitle: 'Portas de mídia',
  mediaHelp: 'O vídeo passa por TCP {tcp} e UDP {udp}: as duas precisam chegar nesta máquina vindas da internet\n(redirecionamento no roteador ou UPnP).',
  mediaChangeQ: 'Mudar essas portas?',
  mediaTcpQ: 'Porta TCP',
  mediaUdpQ: 'Porta UDP',
  mediaBusy: '{proto} {port} está em uso nesta máquina (tudo bem se for a própria Telinha).',

  discordTitle: 'Discord',
  discordTokenHelp: 'Seu app do Discord: discord.com/developers/applications -> New Application,\ndepois Bot -> Reset Token e copie.',
  discordTokenQ: 'Token do bot',
  discordChecking: 'Verificando o token...',
  discordBot: 'Bot: {name} (app id {id})',
  discordTokenRejected: 'O Discord recusou o token; cole de novo.',
  discordUnreachable: 'Não deu pra falar com o Discord: {error}',
  discordGiveUp: 'O Discord é necessário pra terminar; rode telinha setup de novo mais tarde (ou use --no-discord-check).',
  discordOffline: 'O Discord não é consultado (--no-discord-check): os ids são digitados à mão e nada é verificado.',
  tryAgain: 'Tentar de novo?',
  intentsOk: 'Server Members Intent e Presence Intent estão ligados.',
  intentsOn: 'Server Members Intent e Presence Intent foram ligados.',
  intentsApiFailed: 'Não deu pra ligar os intents automaticamente: {error}',
  intentsManual: 'Página Bot -> Privileged Gateway Intents: ligue Server Members Intent e Presence Intent,\ndepois Save Changes.',
  intentsGiveUp: 'Os intents continuam desligados: o bot não consegue entrar ("disallowed intents") até ligar.',
  pressEnterDone: 'Aperte Enter quando terminar',
  secretHelp: 'Página OAuth2 -> Client Secret -> Reset Secret, e copie.',
  secretQ: 'Client secret',
  secretNew: 'Digitar um novo',
  secretOk: 'Client secret aceito.',
  secretRejected: 'O Discord recusou o client secret.',
  secretUnchecked: 'Não deu pra verificar o client secret ({error}); mantendo.',
  redirectOk: 'O redirect URI está cadastrado.',
  redirectHelp: 'O Discord não deixa adicionar o redirect de login pela API. Na página OAuth2:\nRedirects -> Add Redirect, cole isto e clique em Save Changes:',
  redirectQ: 'Adicionou?',
  redirectCheck: 'Sim, verificar de novo',
  redirectSkip: 'Pular por enquanto',
  redirectMissing: 'Ainda não está lá (clicou em Save Changes?).',
  redirectSkipped: 'O login vai falhar até {uri} ser um redirect do app (o telinha doctor verifica).',
  inviteHelp: 'Adicione o bot ao seu servidor com este link (precisa de Gerenciar Servidor lá):',
  openBrowser: 'Abrir no navegador?',
  openFailed: 'Não deu pra abrir um navegador; abra o link à mão.',
  pressEnterInvited: 'Aperte Enter quando o bot estiver no servidor',
  guildNone: 'O bot ainda não está em nenhum servidor.',
  guildMissing: 'O bot não está no servidor {id}.',
  guildMissingInvite: 'O bot não está no servidor {id}; adicione com {url}',
  guildGiveUp: 'O bot ainda não está em nenhum servidor. Adicione com {url} e rode telinha setup de novo.',
  guildOther: 'Outro servidor (adicionar o bot)',
  guildQ: 'A Telinha é pra qual servidor?',
  roleHelp: 'Quem tem este cargo pode entrar nas salas.',
  roleQ: 'Cargo',
  roleEveryone: 'Todo mundo do servidor (@everyone)',
  roleMissing: 'O cargo {id} não existe no servidor.',
  channelsHelp: 'O comando de barra só funciona nestes canais.',
  channelsQ: 'Canais',
  channelsNone: 'O bot não vê nenhum canal de texto em {guild}; dê acesso a um e rode o setup de novo.',
  channelMissing: 'O canal {id} não é um canal de texto que o bot vê.',
  commandQ: 'Nome do comando de barra',
  commandBad: 'Letras minúsculas, dígitos, - ou _, no máximo 32.',
  groupQ: 'Nome do grupo nas páginas e respostas (vazio: o nome do servidor, {name})',
  clientIdQ: 'Id da aplicação (client id)',
  clientIdMismatch: '--client-id {given} não bate com a aplicação do token {id}; usando {id}.',
  guildIdQ: 'Id do servidor (guild)',
  roleIdQ: 'Id do cargo',
  channelIdsQ: 'Ids dos canais (separados por vírgula)',
  idBad: 'Um id do Discord tem de 17 a 20 dígitos.',

  updatesTitle: 'Atualizações',
  updatesHelp: 'Versões estáveis novas se instalam sozinhas quando não tem sala aberta.',
  autoUpdateQ: 'Manter a Telinha atualizada automaticamente?',
  reviewTitle: 'Revisão',
  reviewQ: 'Gravar esta configuração?',
  reviewWrite: 'Gravar',
  reviewRotate: 'Gravar com um cookie secret novo',
  reviewRotateHint: 'desloga todo mundo',
  reviewAbort: 'Cancelar',
  secretGenerated: '(gerado)',
  secretKept: '(mantido)',
  secretSet: '(definido)',
  written: '{file} gravado',
  aclFailed: 'Não deu pra restringir o acesso ao arquivo: {error}',

  binsTitle: 'Programas',
  binsChecking: 'Baixando LiveKit, Caddy / cloudflared...',
  binsOk: 'Programas prontos em {dir}',
  binsFailed: 'O download falhou: {error}. O telinha run tenta de novo ao iniciar.',
  binsByService: 'O serviço baixa o LiveKit, o Caddy / cloudflared sozinho, com o usuário dele, quando inicia.',
  serviceTitle: 'Serviço',
  serviceNeedsBinary: 'Rodando do código-fonte: nenhum serviço é instalado (o binário nativo instala um).',
  serviceUnsupported: 'Sem gerenciador de serviço neste sistema; inicie a Telinha com telinha run.',
  serviceInstalling: 'Instalando o serviço ({kind})...',
  serviceInstalled: 'Serviço instalado ({kind})',
  serviceFailed: 'A instalação do serviço falhou: {error}',
  serviceManual: 'Instale depois: cole isto no PowerShell (o Windows pede direitos de administrador):\n  {cmd}',
  exeCopied: 'Programa copiado pra {path}',
  pathAdded: '{dir} foi adicionado ao seu PATH: terminais novos conhecem o comando telinha.',
  whoamiFailed: 'Não deu pra ler a conta atual do Windows (whoami).',
  uacExplain: 'O Windows pede permissão de administrador uma vez (UAC): pra registrar a tarefa em segundo plano\ne liberar as portas de mídia no firewall.',
  uacDeclined: 'A permissão de administrador não foi dada; o serviço não foi instalado.',
  uacNoResult: 'A instalação elevada não deixou resultado (código de saída {code}).',
  stepTask: 'Tarefa em segundo plano',
  stepFirewall: 'Regras de firewall',
  stepStart: 'Início',
  stepSkipped: '{step}: pulado',
  stepHint: 'Falta fazer à mão: {cmd}',
  lingerWhy: 'Sem isso a Telinha para sempre que você sai desta máquina (o fim de uma sessão SSH conta).',
  sysctlExplain: 'As portas {ports} são menores que 1024: o Linux só deixa o root usar elas, a menos que um ajuste mude.\nUm comando sudo libera as portas a partir da 80 pra todo usuário (vale depois das atualizações):',
  sysctlQ: 'Rodar com sudo agora?',
  sysctlOk: 'Portas a partir da 80 liberadas.',
  sysctlFailed: 'O ajuste não foi feito.',
  highPortsExplain: 'Alternativa: a Telinha escuta na 8443 e o roteador repassa a 443 pública pra 8443\n(sem porta 80; o certificado vem pela 443).',
  highPortsQ: 'Mudar pra porta 8443?',
  highPortsOk: 'HTTPS_PORT=8443, HTTP_PORT=0 gravados; redirecione a 443 pública pra 8443 no roteador.',
  sysctlManual: 'Pra usar 80/443 depois: {cmd}',

  routerTitle: 'Roteador',
  routerNone: 'Nenhum roteador respondeu UPnP, NAT-PMP ou PCP.',
  routerFound: 'Roteador {router}, IP externo {ip}',
  forwardByHand: 'Redirecione estas portas no roteador pra esta máquina: {ports}',
  routerVps: 'Libere estas portas no firewall do provedor (security group / security list) e no firewall desta máquina: {ports}',
  routerVpsUfw: 'O ufw está instalado; se estiver ativo: {cmd}',
  routerVpsFirewalld: 'O firewalld está instalado; se estiver rodando: {cmd}',
  upnpWillMap: 'A Telinha pede {ports} pro roteador enquanto roda (o telinha doctor mostra o resultado).',
  cgnat: 'O IP externo do roteador é de CGNAT da operadora (100.64.0.0/10): nada da internet chega\nnesta rede. Peça um IP público pra operadora, ou rode a Telinha numa VPS.',
  doubleNat: 'O IP externo do roteador é privado: tem um segundo roteador na frente (NAT duplo).\nRedirecione as portas nele também, ou coloque este roteador em modo bridge.',

  startTitle: 'Início',
  waitingStart: 'Esperando a Telinha iniciar...',
  restarting: 'Reiniciando a Telinha com a configuração nova...',
  running: 'A Telinha está rodando.',
  notAnswering: 'A Telinha ainda não responde. O log dela diz o motivo: {log}\n{telinha} doctor --local verifica o resto.',
  certWaiting: 'Esperando o certificado HTTPS (Let\'s Encrypt, em geral menos de um minuto)...',
  certOk: 'Certificado HTTPS no lugar.',
  certPending: 'Ainda sem certificado HTTPS: conseguir um pode levar alguns minutos. Se o doctor apontar isso abaixo, rode {telinha} doctor de novo daqui a uns minutos antes de mudar qualquer coisa.',
  consoleRestart: 'A Telinha roda num console: reinicie ela lá pra usar a configuração nova.',
  startByHand: 'Inicie com: {cmd}',
  doctorTitle: 'Verificando tudo (telinha doctor)',
  doctorProblems: 'O doctor achou problemas: as linhas acima dizem o que corrigir; {telinha} doctor verifica de novo.',
  doctorFailed: 'O doctor não conseguiu rodar: {error}',
  nextTitle: 'Próximos passos',
  nextNative: 'Abra {url} ou digite /{command} num dos canais escolhidos do Discord.\nAs configurações ficam em {file}: rode {telinha} setup de novo pra mudar, {telinha} doctor pra verificar.',
  nextDocker: 'Inicie no host:          cd /opt/telinha && docker compose up -d\nMantenha atualizada:     systemctl enable --now telinha-update.timer\nVerifique:               docker exec -it telinha bun server/src/index.ts doctor',
});

export type SKey = keyof typeof t.en;
