// Texts of `telinha doctor` around the checks (summary, phone test), in EN and
// pt-BR. Shared by the plain output and the terminal UI.
import { defineStrings } from './strings.ts';

export const doctorStrings = defineStrings({
  checking: 'Checking {title}...',
  summary: '{ok} ok, {warn} warning(s), {fail} failure(s), {skip} skipped',
  phoneTitle: 'Phone test',
  phoneOpen: 'Open this on your phone with Wi-Fi OFF (mobile data):',
  phoneWaiting: 'Waiting up to 10 minutes... (Ctrl+C to skip)',
  phoneOpened: 'Opened on the phone, testing...',
  phoneSkipped: 'Phone test skipped.',
  phoneExpired: 'The link expired before the phone finished the test. Run telinha doctor again.',
  phoneNotRunning: 'Start Telinha to run the phone test (telinha service start).',
  phoneNoTty: 'Phone test skipped: it needs an interactive terminal (or pass --no-phone).',
  phoneError: 'Phone test could not start: {error}',
  rowHttps: 'HTTPS',
  rowSignaling: 'LiveKit connection',
  rowPublish: 'Sending video',
  rowInitial: 'First path',
  rowUdp: 'UDP {port}',
  rowTcp: 'TCP {port}',
  rowUdpCloud: 'UDP',
  rowTcpCloud: 'TCP',
  rowTurn: 'TURN/TLS 443',
  latency: '{ms} ms',
  initialPath: '{protocol} to {ip}, {ms} ms',
  initialNone: 'no media path',
  works: 'works',
  worksRtt: 'works, {ms} ms',
  failed: 'failed',
  hintSignaling: 'Telinha is not reachable at PUBLIC_URL from the internet: check the DNS, TLS and router checks above.',
  hintBoth: 'The HTTP side works, but the media ports are closed: open TCP {tcp} and UDP {udp} to this machine (router forwarding at home; the provider\'s firewall or security group on a VPS; and this machine\'s own firewall).',
  hintUdp: 'UDP {udp} is not reachable from the internet: open it to this machine (router forwarding, or the VPS provider\'s firewall); video falls back to TCP, with more delay.',
  hintTcp: 'TCP {tcp} is not reachable from the internet: open it to this machine (router forwarding, or the VPS provider\'s firewall); it is needed where UDP is blocked.',
  hintIp: 'LiveKit advertises {ip}, which is not the public IP {publicIp}: check LIVEKIT_NODE_IP.',
  hintCloudSignaling: 'The phone loaded Telinha but could not connect to LiveKit Cloud: check the livekit-cloud check above (LIVEKIT_CLOUD_URL, API key and secret) or try another network.',
  hintCloudBoth: 'The phone reached Telinha but not LiveKit Cloud over WebRTC (UDP and TCP): that network blocks WebRTC. Nothing to open on your side; try another network.',
  hintCloudUdp: 'UDP to LiveKit Cloud did not work from the phone; video falls back to TCP with more delay. Nothing to open on your side.',
  hintCloudTcp: 'TCP to LiveKit Cloud did not work from the phone; video still works over UDP. Nothing to open on your side.',
  hintTurn: 'TURN over TLS on port 443 did not work from the phone: see the turn check above (DNS record and certificate for {turnHost}).',
  phoneAllGood: 'The phone reached Telinha over UDP and TCP.',
}, {
  checking: 'Verificando {title}...',
  summary: '{ok} ok, {warn} aviso(s), {fail} falha(s), {skip} pulada(s)',
  phoneTitle: 'Teste no celular',
  phoneOpen: 'Abra isto no celular com o Wi-Fi DESLIGADO (dados móveis):',
  phoneWaiting: 'Esperando até 10 minutos... (Ctrl+C pula)',
  phoneOpened: 'Aberto no celular, testando...',
  phoneSkipped: 'Teste no celular pulado.',
  phoneExpired: 'O link expirou antes de o celular terminar o teste. Rode telinha doctor de novo.',
  phoneNotRunning: 'Inicie a Telinha pra fazer o teste no celular (telinha service start).',
  phoneNoTty: 'Teste no celular pulado: ele precisa de um terminal interativo (ou use --no-phone).',
  phoneError: 'O teste no celular não pôde começar: {error}',
  rowHttps: 'HTTPS',
  rowSignaling: 'Conexão com o LiveKit',
  rowPublish: 'Envio de vídeo',
  rowInitial: 'Primeiro caminho',
  rowUdp: 'UDP {port}',
  rowTcp: 'TCP {port}',
  rowUdpCloud: 'UDP',
  rowTcpCloud: 'TCP',
  rowTurn: 'TURN/TLS 443',
  latency: '{ms} ms',
  initialPath: '{protocol} até {ip}, {ms} ms',
  initialNone: 'nenhum caminho de mídia',
  works: 'funciona',
  worksRtt: 'funciona, {ms} ms',
  failed: 'falhou',
  hintSignaling: 'A Telinha não é acessível pela internet no PUBLIC_URL: veja as verificações de DNS, TLS e roteador acima.',
  hintBoth: 'O lado HTTP funciona, mas as portas de mídia estão fechadas: libere TCP {tcp} e UDP {udp} pra esta máquina (redirecionamento no roteador em casa; o firewall ou security group do provedor numa VPS; e o firewall desta máquina).',
  hintUdp: 'A porta UDP {udp} não é acessível pela internet: libere pra esta máquina (redirecionamento no roteador, ou o firewall do provedor da VPS); o vídeo cai pro TCP, com mais atraso.',
  hintTcp: 'A porta TCP {tcp} não é acessível pela internet: libere pra esta máquina (redirecionamento no roteador, ou o firewall do provedor da VPS); ela é necessária onde o UDP é bloqueado.',
  hintIp: 'O LiveKit anuncia {ip}, que não é o IP público {publicIp}: confira o LIVEKIT_NODE_IP.',
  hintCloudSignaling: 'O celular abriu a Telinha mas não conseguiu conectar no LiveKit Cloud: veja a verificação livekit-cloud acima (LIVEKIT_CLOUD_URL, chave e segredo da API) ou tente outra rede.',
  hintCloudBoth: 'O celular chegou na Telinha mas não no LiveKit Cloud por WebRTC (UDP e TCP): essa rede bloqueia WebRTC. Não há nada pra abrir do seu lado; tente outra rede.',
  hintCloudUdp: 'O UDP até o LiveKit Cloud não funcionou no celular; o vídeo cai pro TCP, com mais atraso. Não há nada pra abrir do seu lado.',
  hintCloudTcp: 'O TCP até o LiveKit Cloud não funcionou no celular; o vídeo ainda funciona por UDP. Não há nada pra abrir do seu lado.',
  hintTurn: 'O TURN sobre TLS na porta 443 não funcionou no celular: veja a verificação turn acima (registro DNS e certificado de {turnHost}).',
  phoneAllGood: 'O celular chegou na Telinha por UDP e TCP.',
});
export type DoctorStrKey = Parameters<typeof doctorStrings>[1];
